//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HDT.Plugins.Graveyard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HDT.Plugins.Graveyard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathrattle.
        /// </summary>
        public static string Deathrattle {
            get {
                return ResourceManager.GetString("Deathrattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player deathrattle minions that have died.
        /// </summary>
        public static string DeathrattleDescription {
            get {
                return ResourceManager.GetString("DeathrattleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Horsemen.
        /// </summary>
        public static string FourHorsemen {
            get {
                return ResourceManager.GetString("FourHorsemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Friendly {
            get {
                return ResourceManager.GetString("Friendly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all player minions that have died.
        /// </summary>
        public static string FriendlyDescription {
            get {
                return ResourceManager.GetString("FriendlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graveyard.
        /// </summary>
        public static string Graveyard {
            get {
                return ResourceManager.GetString("Graveyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays minions that have died this game. Includes specialized displays:
        ///
        ///- Questline progress
        ///- Resurrection chance
        ///- Deathrattle minions
        ///
        ///Go to Settings for the full list of cards supported.
        /// </summary>
        public static string GraveyardDescription {
            get {
                return ResourceManager.GetString("GraveyardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demons.
        /// </summary>
        public static string Guldan {
            get {
                return ResourceManager.GetString("Guldan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons Used.
        /// </summary>
        public static string HoardPillager {
            get {
                return ResourceManager.GetString("HoardPillager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Horizontal {
            get {
                return ResourceManager.GetString("Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Riff Played.
        /// </summary>
        public static string LastRiff {
            get {
                return ResourceManager.GetString("LastRiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Graveyards.
        /// </summary>
        public static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Spell by School.
        /// </summary>
        public static string Multicaster {
            get {
                return ResourceManager.GetString("Multicaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent.
        /// </summary>
        public static string Opponent {
            get {
                return ResourceManager.GetString("Opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show opponent deathrattle minions that have died.
        /// </summary>
        public static string OpponentDeathrattleDescription {
            get {
                return ResourceManager.GetString("OpponentDeathrattleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all opponent minions that have died.
        /// </summary>
        public static string OpponentDescription {
            get {
                return ResourceManager.GetString("OpponentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show opponent questline progress.
        /// </summary>
        public static string OpponentQuestlineDescription {
            get {
                return ResourceManager.GetString("OpponentQuestlineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical or Horizontal view stacking.
        /// </summary>
        public static string OrientationDescription {
            get {
                return ResourceManager.GetString("OrientationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issue.
        /// </summary>
        public static string PluginIssues {
            get {
                return ResourceManager.GetString("PluginIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to README.
        /// </summary>
        public static string PluginReadme {
            get {
                return ResourceManager.GetString("PluginReadme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Release.
        /// </summary>
        public static string PluginReleases {
            get {
                return ResourceManager.GetString("PluginReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questline.
        /// </summary>
        public static string Questline {
            get {
                return ResourceManager.GetString("Questline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player questline progress.
        /// </summary>
        public static string QuestlineDescription {
            get {
                return ResourceManager.GetString("QuestlineDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undead.
        /// </summary>
        public static string Reanimate {
            get {
                return ResourceManager.GetString("Reanimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relics Cast.
        /// </summary>
        public static string Relic {
            get {
                return ResourceManager.GetString("Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resurrect.
        /// </summary>
        public static string Resurrect {
            get {
                return ResourceManager.GetString("Resurrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the resurrect chance of player minions that have died.
        /// </summary>
        public static string ResurrectDescription {
            get {
                return ResourceManager.GetString("ResurrectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string SettingsCardsTitle {
            get {
                return ResourceManager.GetString("SettingsCardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string SettingsDisplayTitle {
            get {
                return ResourceManager.GetString("SettingsDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string SettingsHorizontal {
            get {
                return ResourceManager.GetString("SettingsHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Screen Position (Left &lt;-&gt; Right).
        /// </summary>
        public static string SettingsHorizontalTooltip {
            get {
                return ResourceManager.GetString("SettingsHorizontalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string SettingsPositionTitle {
            get {
                return ResourceManager.GetString("SettingsPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default.
        /// </summary>
        public static string SettingsResetButtonTooltip {
            get {
                return ResourceManager.GetString("SettingsResetButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graveyard Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string SettingsVertical {
            get {
                return ResourceManager.GetString("SettingsVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Screen Position (Top &lt;-&gt; Bottom).
        /// </summary>
        public static string SettingsVerticalTooltip {
            get {
                return ResourceManager.GetString("SettingsVerticalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI:7.
        /// </summary>
        public static string SI7 {
            get {
                return ResourceManager.GetString("SI7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Class Cards.
        /// </summary>
        public static string TessGreymane {
            get {
                return ResourceManager.GetString("TessGreymane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Graveyards.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Vertical {
            get {
                return ResourceManager.GetString("Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beasts.
        /// </summary>
        public static string WitchingHour {
            get {
                return ResourceManager.GetString("WitchingHour", resourceCulture);
            }
        }
    }
}
