name: Build+Upload
on:
  workflow_dispatch:

env: 
  PROJECT: ${{ 'Graveyard' }}

jobs:
  build-and-upload:
    runs-on: windows-latest      
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - uses: NuGet/setup-nuget@v1.0.5 
      - run: .\scripts\update-libraries.ps1
      - run: nuget restore "${{ env.PROJECT }}.sln"
      - id: set_version
        run: |
          $build = 2000 + $Env:GITHUB_RUN_NUMBER
          $buildVersion = .\scripts\assembly-version.ps1 -project "${{ env.PROJECT }}" -build $build -overrideVersion ${{ github.ref }}
          echo "::set-output name=buildVersion::$buildVersion"
      - run: msbuild.exe "${{ env.PROJECT }}.sln" /p:platform="x86" /p:configuration="Release"
      - uses: actions/upload-artifact@v2.2.3
        with:
          name: ${{ env.PROJECT }}-v${{ steps.set_version.outputs.buildVersion }}
          path: .\${{ env.PROJECT }}\bin\x86\Release\${{ env.PROJECT }}.dll
